pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:davipro_34/cours_c.git
          - cd cours_c.git
          - git push --mirror git@github.com:davipro34/Cours_C.git